services:
  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - capybara
    # restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - 8443:443
    develop:
      watch:
        - path: ./nginx/nginx.conf
          action: rebuild

  frontend:
    container_name: frontend
    build: ./frontend
    networks:
      - capybara
    # restart: always
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/next.config.ts
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  backend:
    container_name: backend
    build: ./backend
    networks:
      - capybara
    # restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
      - ./uploads:/app/uploads
    ports:
      - 3001:3001
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
          ignore:
            - uploads/

networks:
  capybara:
    driver: bridge